/* Cards */
export const NEWS_GETALL_REQUEST = 'NEWS_GETALL_REQUEST'
export const NEWS_GETALL_SUCCESS = 'NEWS_GETALL_SUCCESS'
export const NEWS_GETALL_FAILURE = 'NEWS_GETALL_FAILURE'
export const NEWS_GETALL_UPDATE = 'NEWS_GETALL_UPDATE'

/* Aside */

export const ASIDE_GETALL_REQUEST = 'ASIDE_GETALL_REQUEST'
export const ASIDE_GETALL_SUCCESS = 'ASIDE_GETALL_SUCCESS'
export const ASIDE_GETALL_FAILURE = 'ASIDE_GETALL_FAILURE'

/* Table */

export const Table_GETALL_REQUEST = 'Table_GETALL_REQUEST'
export const Table_GETALL_SUCCESS = 'Table_GETALL_SUCCESS'
export const Table_GETALL_FAILURE = 'Table_GETALL_FAILURE'

/* Results */

export const RESULTS_GETALL_REQUEST = 'RESULTS_GETALL_REQUEST'
export const RESULTS_GETALL_SUCCESS = 'RESULTS_GETALL_SUCCESS'
export const RESULTS_GETALL_FAILURE = 'RESULTS_GETALL_FAILURE'